nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: "bastion_ip"

  # Wazuh server nodes
  # If there is more than one Wazuh server
  # node, each one must have a node_type
  server:
    - name: wazuh-1
      ip: "bastion_ip"

  # Wazuh dashboard nodes
  dashboard:
    - name: dashboard
      ip: "bastion_ip"
